<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__confirmPassword</name>
   <tag></tag>
   <elementGuidId>9475beab-343f-4188-a654-6f065918d03f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#«r4»</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='«r4»']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Nhập lại mật khẩu của bạn&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>40f52144-fe26-495b-b5d1-c69093b258bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>d1a60dc3-e02e-4ef8-a293-8aca0b9226a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>«r4»</value>
      <webElementGuid>307cdc9a-27ce-47f2-9447-ab4cf94945c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Nhập lại mật khẩu của bạn</value>
      <webElementGuid>fcf15abd-f33b-4ed4-a9ae-556ad6f4104f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiInputBase-input MuiOutlinedInput-input MuiInputBase-inputAdornedStart MuiInputBase-inputAdornedEnd css-qve9l1-MuiInputBase-input-MuiOutlinedInput-input</value>
      <webElementGuid>2cf14a1d-eb30-43bd-96a2-acc7d60069cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>755707fb-b8d4-409e-919c-a63ed571af0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>confirmPassword</value>
      <webElementGuid>86f95db1-81bd-4fae-8798-868b8c5d2699</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;«r4»&quot;)</value>
      <webElementGuid>513a78ec-3f96-47b5-b7e7-91bc106de63d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='«r4»']</value>
      <webElementGuid>7f30550e-1adf-4aa3-bdba-c894572cb821</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/div/div/div/form/div[4]/div/div/input</value>
      <webElementGuid>d113c626-93e5-489d-9c96-12d3a5301dae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/input</value>
      <webElementGuid>548281fa-f13a-483e-b8de-6d8d665ca8f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = '«r4»' and @placeholder = 'Nhập lại mật khẩu của bạn' and @type = 'password' and @name = 'confirmPassword']</value>
      <webElementGuid>98bc2f0d-669f-476d-8b81-4d730388039c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
