<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Ngy sinh_terms</name>
   <tag></tag>
   <elementGuidId>45cdc30c-d0a3-4caf-bc07-05b4e09d20ae</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;terms&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='terms']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Tôi đồng ý với Điều khoản sử dụng và Chính sách bảo mật&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>736b8901-dc48-4ae8-8f22-466e251390c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-indeterminate</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>7d92faad-7f2a-45b8-93fe-5fa98431ded6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>PrivateSwitchBase-input css-12xagqm-MuiSwitchBase-root</value>
      <webElementGuid>0ed0ef02-267d-44d9-a65f-16208e753ff5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>91b3a27f-8671-4c47-93d3-d3f4afc4e04e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>terms</value>
      <webElementGuid>399bc3f4-46f6-4d47-a73a-c06e362cc0f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/main[1]/div[@class=&quot;MuiBox-root css-m0pgy8&quot;]/div[@class=&quot;MuiPaper-root MuiPaper-elevation MuiPaper-rounded MuiPaper-elevation1 MuiCard-root css-1sotj5k-MuiPaper-root-MuiCard-root&quot;]/div[@class=&quot;MuiBox-root css-17867ir&quot;]/form[@class=&quot;MuiBox-root css-1ouw2vm&quot;]/div[@class=&quot;MuiBox-root css-uewl2b&quot;]/label[@class=&quot;MuiFormControlLabel-root MuiFormControlLabel-labelPlacementEnd css-19opgx6-MuiFormControlLabel-root&quot;]/span[@class=&quot;MuiButtonBase-root MuiCheckbox-root MuiCheckbox-colorPrimary MuiCheckbox-sizeMedium PrivateSwitchBase-root MuiCheckbox-root MuiCheckbox-colorPrimary MuiCheckbox-sizeMedium MuiCheckbox-root MuiCheckbox-colorPrimary MuiCheckbox-sizeMedium css-1fxkaa2-MuiButtonBase-root-MuiSwitchBase-root-MuiCheckbox-root&quot;]/input[@class=&quot;PrivateSwitchBase-input css-12xagqm-MuiSwitchBase-root&quot;]</value>
      <webElementGuid>5271acbc-e280-4a7d-a081-3cc222c5f970</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='terms']</value>
      <webElementGuid>812334d7-9bcd-40a1-8724-ca20ac00b92c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/div/div/div/form/div[8]/label/span/input</value>
      <webElementGuid>f39752ab-d77e-489b-a0cd-e15f30a6ceee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/input</value>
      <webElementGuid>89c48698-66f4-489b-8cf1-d2378381a3cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'terms']</value>
      <webElementGuid>175ba67f-5c23-4977-85c7-7db71f5ca269</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
