<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>RegistrationTestSuite</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>f09304ca-46b8-4664-ae8e-2cd41b005d2d</testSuiteGuid>
   <testCaseLink>
      <guid>7d35e0f9-9adc-4580-b341-2cb31b173a5d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/RegistrationFunction/RegistrationEmpt2Password-TC5</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b995ff8e-dc66-4aeb-82e6-d4e162e94a3d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7f9a292a-a266-4963-ab87-c6de67d4e55d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6d8bc5a3-3933-4aa8-be3e-490e78380c02</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6a1082dc-09a2-46e5-8673-99deb2bc8070</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>75d3a893-0074-4492-b717-9341e3877354</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fbf0fa87-0808-43b8-91d0-7ff2e740eb51</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>628245a2-ca42-4349-98b0-8305ea468480</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>48f81aeb-3aa7-4b83-932b-c5458f257248</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/RegistrationFunction/RegistrationEmptUsername-TC11</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>45ced619-7077-4db6-867f-3b070c9679ae</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bce9d11d-0f8d-4d81-baa8-041634afdf96</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e1c9a4db-61dc-4c44-929e-c9233c77995c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>69280e04-f33d-49af-89d9-8556c211096c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ff863b4a-9b90-4694-bed4-ef69cb2c13fe</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fa101260-105b-4f1e-a5fb-8fbc80af3791</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d40d80c7-09e5-415a-b1d5-e93ed7a8fcb3</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c7bf7572-481c-41b5-a867-edb65a637875</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/RegistrationFunction/Registration</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>8bbc985c-2a8d-4f33-ac68-47516fdec088</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/RegistrationDataTest</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>8bbc985c-2a8d-4f33-ac68-47516fdec088</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>username</value>
         <variableId>949f9a06-2dea-4baf-bb16-01025dbd9221</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>8bbc985c-2a8d-4f33-ac68-47516fdec088</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>password</value>
         <variableId>0cfa2c42-b32e-43f1-aa73-c3f3a198c5a6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>8bbc985c-2a8d-4f33-ac68-47516fdec088</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>confirmPassword</value>
         <variableId>2ffcb278-dd2f-4553-8bef-edbc3f7eae14</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>8bbc985c-2a8d-4f33-ac68-47516fdec088</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>email</value>
         <variableId>8425b13d-39a8-4cc2-86f5-c3199f170588</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>8bbc985c-2a8d-4f33-ac68-47516fdec088</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>phoneNumber</value>
         <variableId>b51fec1d-0b29-4687-9eaf-327ffabf7610</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>8bbc985c-2a8d-4f33-ac68-47516fdec088</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>fullname</value>
         <variableId>b6ce968c-e07c-4874-9edc-84cf21533aee</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>8bbc985c-2a8d-4f33-ac68-47516fdec088</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>expected_msg</value>
         <variableId>5f3620c6-ba65-4b43-a6cf-1cfbcf57d12a</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
