<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>accountBox</name>
   <tag></tag>
   <elementGuidId>2ccb9b06-f3ea-4ce6-bc3b-7916e7a64b9a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/header/div/div[2]/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.MuiBox-root.css-1415nmb</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>div >> internal:has-text=&quot;Lương Minh Nhật&quot;i >> nth=4</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>c76c44bc-cb15-49be-9bb8-22b5fee3df75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiBox-root css-1415nmb</value>
      <webElementGuid>ccae38ef-771f-4c12-b2d2-b0c412dd19df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Lương Minh Nhật</value>
      <webElementGuid>1eb1bad2-81c8-4eab-8dc5-d95a08edb952</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/header[1]/div[@class=&quot;header-container&quot;]/div[@class=&quot;user-actions&quot;]/div[@class=&quot;MuiBox-root css-18nbiav&quot;]/div[@class=&quot;MuiBox-root css-1415nmb&quot;]</value>
      <webElementGuid>5dc6642a-75ee-4929-90c8-02e1ccccb133</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/header/div/div[2]/div/div</value>
      <webElementGuid>2876a8e2-7eac-4869-996c-06240c97fa7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Trang chủ'])[1]/preceding::div[2]</value>
      <webElementGuid>73c5c8cd-cfd4-41f8-871c-5fae8142bd3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Khóa học'])[1]/preceding::div[2]</value>
      <webElementGuid>58b4684c-3d4a-48c5-94eb-ae062f0660ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div</value>
      <webElementGuid>3cc77b68-8594-4387-9cd3-ae1c6b92915f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Lương Minh Nhật' or . = 'Lương Minh Nhật')]</value>
      <webElementGuid>643d025a-4b08-48e1-b8bc-22f6455a0fd6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
